### ISSUE TITLE
Kaggel Kernel link not working

### ISSUE THREAD

**Issue by jayrodge** [vingkan/crash#1]
Hey Vinesh, The kaggle kernel link in the readme file is not working. Can you check?

**Comment by vingkan** [comment]
Hi @jayrodge, I will take a look this evening and update it. Thanks for letting me know!

**Comment by vingkan** [comment]
Hi @jayrodge, the link did not work because I forgot to make the kernel public. I have now made the Kaggle kernel and dataset public. Let me know if the link in the README works for you now.
